title = "The Markdown Handbook"

description = "The Markdown Handbook is your reference to everything markdown."

base_url = "https://md-handbook.com"

author = "The Markdown Handbook"

default_language = "en"

# SASS

compile_sass = false

# TAXONOMIES

taxonomies = [
    { name = "tags", paginate_by = 10, feed = true },
]

# FEEDS

generate_feeds = true
feed_filenames = ["rss.xml"]

# SEARCH INDEX

build_search_index = true

# MARKDOWN

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light" # kronuz

[extra]
# Put all your custom variables here
